FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o product-service cmd/product-service/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/product-service .
EXPOSE 8082
CMD ["./product-service"]
