FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o order-service cmd/order-service/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/order-service .
EXPOSE 8083
CMD ["./order-service"]
